### ISSUE TITLE
可能的BUG：Tokenizer的BOS没有被初始化，导致其值为None报错。

### ISSUE THREAD

**Issue by Little-Otter7** [LindiaC/ChatGLM2-With-Rua-Tutorial#1]
> _**multiprocess.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 520, in wrapper
>     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
>   File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 487, in wrapper
>     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
>   File "/opt/conda/lib/python3.10/site-packages/datasets/fingerprint.py", line 458, in wrapper
>     out = func(self, *args, **kwargs)
>   File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2339, in _map_single
>     batch = apply_function_on_filtered_inputs(
>   File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2220, in apply_function_on_filtered_inputs
>     processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
>   File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1915, in decorated
>     result = f(decorated_item, *args, **kwargs)
>   File "/kaggle/input/littleotterschat/ChatGLM-6B/ptuning/main.py", line 219, in preprocess_function_train
>     context_length = input_ids.index(tokenizer.bos_token_id)
> ValueError: None is not in list**_
以上为报错的代码，微信聊天记录导出应用版本为0.2.6.

**Comment by LindiaC** [comment]
您好，我提供的代码是ChatGLM2版本的，ChatGLM2与ChatGLM训练存在多处不同（比如train.sh就不一样），有可能tokenizer存在差异，要不您试试换到ChatGLM2，这样可以更好地帮您解决问题？   
（哎呀发现是我原来把clone的命令写成一代的了，已修改readme，现在应该对了......带来不便非常抱歉，感谢您的指出）

**Comment by Little-Otter7** [comment]
Thanks，已经开始跑了！
